LOAD_CONST(code), LOAD_CONST('downloader'), MAKE_FUNCTION, STORE_NAME(downloader)
    LOAD_FAST(var), LOAD_CONST(1), COMPARE_OP(==), POP_JUMP_IF_FALSE{244}
    LOAD_GLOBAL(enlighten), LOAD_METHOD(get_manager), CALL_METHOD, STORE_FAST(MANAGER)
    LOAD_GLOBAL(requests.get), LOAD_FAST(url), LOAD_CONST(True), LOAD_CONST(('stream',)), CALL_FUNCTION_KW{2}, STORE_FAST(r)
    LOAD_FAST(r.status_code), LOAD_CONST(200), COMPARE_OP(==), POP_JUMP_IF_TRUE{50}, LOAD_ASSERTION_ERROR, LOAD_FAST(r.status_code), CALL_FUNCTION{1}, RAISE_VARARGS{1}
    LOAD_GLOBAL(int), LOAD_FAST(r.headers), LOAD_METHOD(get), LOAD_CONST('Content-Length'), LOAD_CONST('0'), CALL_METHOD{2}, CALL_FUNCTION{1}, JUMP_IF_TRUE_OR_POP{70}, |70|dlen = None

    LOAD_FAST(MANAGER.counter), LOAD_CONST(('color', 'total', 'unit', 'leave')), CALL_FUNCTION_KW{4}, SETUP_WITH(to 226), SETUP_WITH(to 196)
    LOAD_CONST('green')
    LOAD_FAST(dlen), JUMP_IF_FALSE_OR_POP{94}, LOAD_GLOBAL(math), LOAD_METHOD(ceil), LOAD_FAST(dlen), LOAD_CONST(1048576), BINARY_TRUE_DIVIDE, CALL_METHOD{1}
    LOAD_CONST('MiB')
    LOAD_CONST(False)
    STORE_FAST(ctr), LOAD_GLOBAL(open), LOAD_FAST(path), LOAD_CONST('wb'), LOAD_CONST(16777216), LOAD_CONST(('buffering',)), CALL_FUNCTION_KW{3}, STORE_FAST(f)
    LOAD_FAST(r.iter_content), LOAD_CONST(1048576), LOAD_CONST(('chunk_size',)), CALL_FUNCTION_KW{1}, GET_ITER, FOR_ITER(to 182), STORE_FAST(chunk)
    LOAD_GLOBAL(print), LOAD_FAST(chunk), LOAD_CONST(-16), LOAD_CONST(None), BUILD_SLICE{2}, BINARY_SUBSCR, LOAD_METHOD(hex), CALL_METHOD, LOAD_METHOD(upper), CALL_METHOD, CALL_FUNCTION{1}, POP_TOP
    LOAD_FAST(f), LOAD_METHOD(write), LOAD_FAST(chunk), CALL_METHOD{1}, POP_TOP
    LOAD_FAST(ctr), LOAD_METHOD(update), CALL_METHOD, POP_TOP, JUMP_ABSOLUTE{134}, POP_BLOCK, LOAD_CONST(None), DUP_TOP, DUP_TOP, CALL_FUNCTION{3}, POP_TOP, JUMP_FORWARD(to 212), WITH_EXCEPT_START, POP_JUMP_IF_TRUE{202}, RERAISE, POP_TOP, POP_TOP, POP_TOP, POP_EXCEPT, POP_TOP, POP_BLOCK, LOAD_CONST(None), DUP_TOP, DUP_TOP, CALL_FUNCTION{3}, POP_TOP, JUMP_FORWARD(to 242), WITH_EXCEPT_START, POP_JUMP_IF_TRUE{232}, RERAISE, POP_TOP, POP_TOP, POP_TOP, POP_EXCEPT, POP_TOP, JUMP_FORWARD(to 390)

    |244|open(path, 'wb'), SETUP_WITH(to 372), STORE_FAST(f)
    LOAD_GLOBAL(requests.get), LOAD_FAST(url), LOAD_CONST(True), LOAD_CONST(('stream',)), CALL_FUNCTION_KW{2}, STORE_FAST(response)
    LOAD_FAST(response.headers), LOAD_METHOD(get), LOAD_CONST('content-length'), CALL_METHOD{1}, STORE_FAST(total)

    LOAD_FAST(total), LOAD_CONST(None), IS_OP, EXTENDED_ARG{1}, POP_JUMP_IF_FALSE{306}
    LOAD_FAST(f), LOAD_METHOD(write), LOAD_FAST(response.content), CALL_METHOD{1}, POP_TOP, JUMP_FORWARD(to 358)

    total = |306|int(total)
    LOAD_FAST(response.iter_content), LOAD_CONST(('chunk_size',)), CALL_FUNCTION_KW{1}, GET_ITER, FOR_ITER(to 358), STORE_FAST(data)
    LOAD_GLOBAL(max), LOAD_GLOBAL(int), LOAD_FAST(total), LOAD_CONST(1000), BINARY_TRUE_DIVIDE, CALL_FUNCTION{1}, LOAD_CONST(1048576), CALL_FUNCTION{2}

    LOAD_FAST(f), LOAD_METHOD(write), LOAD_FAST(data), CALL_METHOD{1}, POP_TOP, EXTENDED_ARG{1}, JUMP_ABSOLUTE{340}, POP_BLOCK, LOAD_CONST(None), DUP_TOP, DUP_TOP, CALL_FUNCTION{3}, POP_TOP, JUMP_FORWARD(to 390), WITH_EXCEPT_START, EXTENDED_ARG{1}, POP_JUMP_IF_TRUE{380}, RERAISE, POP_TOP, POP_TOP, POP_TOP, POP_EXCEPT, POP_TOP, return |390|None


LOAD_CONST(code), LOAD_CONST('check_ram'), MAKE_FUNCTION, STORE_NAME(check_ram)
    LOAD_GLOBAL(psutil), LOAD_METHOD(virtual_memory), CALL_METHOD, LOAD_ATTR(total), STORE_FAST(byte)

    LOAD_FAST(byte), LOAD_CONST(1024), COMPARE_OP(<), POP_JUMP_IF_FALSE{44}
    LOAD_FAST(byte), LOAD_CONST('.2f'), FORMAT_VALUE(with format), STORE_FAST(size)
    round(float(size)), LOAD_CONST(1024), BINARY_MULTIPLY, STORE_FAST(size)
    JUMP_ABSOLUTE{54}
    LOAD_FAST(byte), LOAD_CONST(1024), BINARY_TRUE_DIVIDE, STORE_FAST(byte), JUMP_ABSOLUTE{10}
    LOAD_GLOBAL(int), LOAD_FAST(size), LOAD_CONST(0.8), BINARY_MULTIPLY, CALL_FUNCTION{1}, STORE_FAST(bufor)
    LOAD_GLOBAL(int), LOAD_FAST(allocated), LOAD_METHOD(replace), LOAD_CONST('M'), LOAD_CONST(''), CALL_METHOD{2}, CALL_FUNCTION{1}, LOAD_FAST(bufor), COMPARE_OP(>), POP_JUMP_IF_FALSE{114}
    LOAD_GLOBAL(print), CALL_FUNCTION{1}, POP_TOP
    LOAD_CONST('Cannot asing more ram than '), LOAD_FAST(bufor), FORMAT_VALUE{(None, False)}, LOAD_CONST('MB (80% of amount of available RAM ('), LOAD_FAST(size), FORMAT_VALUE{(None, False)}, LOAD_CONST(') )'), BUILD_STRING{5}

    exit(), return |114|None


LOAD_CONST(code), LOAD_CONST('pliki'), MAKE_FUNCTION, STORE_NAME(pliki)
    i = 0
    LOAD_FAST(sciezka), FORMAT_VALUE{(None, False)}, LOAD_CONST('/logs-setup'), BUILD_STRING{2}, STORE_FAST(pathh)


    LOAD_GLOBAL(path), LOAD_METHOD(exists), LOAD_FAST(pathh), CALL_METHOD{1}, LOAD_CONST(False), COMPARE_OP(==), POP_JUMP_IF_FALSE{38}
    LOAD_GLOBAL(os), LOAD_METHOD(mkdir), LOAD_FAST(pathh), CALL_METHOD{1}, POP_TOP
    LOAD_GLOBAL(path), LOAD_METHOD(exists), LOAD_FAST(pathh), FORMAT_VALUE{(None, False)}, LOAD_CONST('/.SORT_BY_MODIFICATION_TIME.txt'), BUILD_STRING{2}, CALL_METHOD{1}, LOAD_CONST(False), COMPARE_OP(==), POP_JUMP_IF_FALSE{78}
    LOAD_GLOBAL(open), LOAD_FAST(pathh), FORMAT_VALUE{(None, False)}, LOAD_CONST('/.SORT_BY_MODIFICATION_TIME.txt'), BUILD_STRING{2}, LOAD_CONST('w'), CALL_FUNCTION{2}, LOAD_METHOD(close), CALL_METHOD, POP_TOP
    LOAD_GLOBAL(path), LOAD_METHOD(exists), LOAD_FAST(pathh), FORMAT_VALUE{(None, False)}, LOAD_CONST('/'), LOAD_GLOBAL(now_date), FORMAT_VALUE{(None, False)}, LOAD_CONST('-9.log'), BUILD_STRING{4}, CALL_METHOD{1}, LOAD_CONST(True), COMPARE_OP(==), POP_JUMP_IF_FALSE{126}
    LOAD_GLOBAL(os), LOAD_METHOD(remove), LOAD_FAST(pathh), FORMAT_VALUE{(None, False)}, LOAD_CONST('/'), LOAD_GLOBAL(now_date), FORMAT_VALUE{(None, False)}, LOAD_CONST('-9.log'), BUILD_STRING{4}, CALL_METHOD{1}, POP_TOP
    LOAD_GLOBAL(path), LOAD_METHOD(exists), LOAD_FAST(pathh), FORMAT_VALUE{(None, False)}, LOAD_CONST('/'), LOAD_GLOBAL(now_date), FORMAT_VALUE{(None, False)}, LOAD_CONST('.log'), BUILD_STRING{4}, CALL_METHOD{1}, LOAD_CONST(True), COMPARE_OP(==), POP_JUMP_IF_FALSE{238}
    LOAD_GLOBAL(path), LOAD_METHOD(exists), LOAD_FAST(pathh), FORMAT_VALUE{(None, False)}, LOAD_CONST('/'), LOAD_GLOBAL(now_date), FORMAT_VALUE{(None, False)}, LOAD_CONST('-'), LOAD_FAST(i), FORMAT_VALUE{(None, False)}, LOAD_CONST('.log'), BUILD_STRING{6}, CALL_METHOD{1}, LOAD_CONST(True), COMPARE_OP(==), POP_JUMP_IF_FALSE{194}
    LOAD_FAST(i), LOAD_CONST(1), BINARY_ADD, STORE_FAST(i), JUMP_ABSOLUTE{152}
    LOAD_GLOBAL(os), LOAD_METHOD(rename), LOAD_FAST(pathh), FORMAT_VALUE{(None, False)}, LOAD_CONST('/'), LOAD_GLOBAL(now_date), FORMAT_VALUE{(None, False)}, LOAD_CONST('.log'), BUILD_STRING{4}, LOAD_FAST(pathh), FORMAT_VALUE{(None, False)}, LOAD_CONST('/'), LOAD_GLOBAL(now_date), FORMAT_VALUE{(None, False)}, LOAD_CONST('-'), LOAD_FAST(i), FORMAT_VALUE{(None, False)}, LOAD_CONST('.log'), BUILD_STRING{6}, CALL_METHOD{2}, POP_TOP, JUMP_FORWARD(to 290)

    LOAD_GLOBAL(path), LOAD_METHOD(exists), LOAD_FAST(pathh), FORMAT_VALUE{(None, False)}, LOAD_CONST('/latest.log'), BUILD_STRING{2}, CALL_METHOD{1}, LOAD_CONST(True), COMPARE_OP(==), EXTENDED_ARG{1}, POP_JUMP_IF_FALSE{290}
    LOAD_GLOBAL(os), LOAD_METHOD(rename), CALL_METHOD{2}, POP_TOP, return |290|None
    LOAD_FAST(pathh), FORMAT_VALUE{(None, False)}, LOAD_CONST('/latest.log'), BUILD_STRING{2}
    LOAD_FAST(pathh), FORMAT_VALUE{(None, False)}, LOAD_CONST('/'), LOAD_GLOBAL(now_date), FORMAT_VALUE{(None, False)}, LOAD_CONST('.log'), BUILD_STRING{4}



LOAD_NAME(__name__), LOAD_CONST('__main__'), COMPARE_OP(==), EXTENDED_ARG{8}, POP_JUMP_IF_FALSE{2246}
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(datetime), STORE_NAME(datetime)
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(logging), STORE_NAME(logging)
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(os), STORE_NAME(os)
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(subprocess), STORE_NAME(subprocess)
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(sys), STORE_NAME(sys)
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(time), STORE_NAME(time)
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(math), STORE_NAME(math)
LOAD_CONST(0), LOAD_CONST(('path',)), IMPORT_NAME(os), IMPORT_FROM(path), STORE_NAME(path), POP_TOP
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(win32com.client), STORE_NAME(win32com)

try(to 196):
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(configparser), STORE_NAME(configparser)
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(zipfile), STORE_NAME(zipfile)
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(psutil), STORE_NAME(psutil)
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(coloredlogs), STORE_NAME(coloredlogs)
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(PySide2), STORE_NAME(PySide2)
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(requests), STORE_NAME(requests)
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(enlighten), STORE_NAME(enlighten)
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(pypresence), STORE_NAME(pypresence)
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(winshell), STORE_NAME(winshell)
LOAD_CONST(0), LOAD_CONST(None), IMPORT_NAME(pythoncom), STORE_NAME(pythoncom), POP_BLOCK, JUMP_FORWARD(to 348)
DUP_TOP, LOAD_NAME(ImportError), EXTENDED_ARG{1}, JUMP_IF_NOT_EXC_MATCH{346}, POP_TOP, POP_TOP, POP_TOP
LOAD_NAME(os), LOAD_METHOD(system), LOAD_CONST('pip install doctext'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(os), LOAD_METHOD(system), LOAD_CONST('pip install requests'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(os), LOAD_METHOD(system), LOAD_CONST('pip install PySide2'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(os), LOAD_METHOD(system), LOAD_CONST('pip install zipfile'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(os), LOAD_METHOD(system), LOAD_CONST('pip install coloredlogs'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(os), LOAD_METHOD(system), LOAD_CONST('pip install configparser'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(os), LOAD_METHOD(system), LOAD_CONST('pip install enlighten'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(os), LOAD_METHOD(system), LOAD_CONST('pip install psutil'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(os), LOAD_METHOD(system), LOAD_CONST('pip install pypresence'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(os), LOAD_METHOD(system), LOAD_CONST('pip install winshell'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(os), LOAD_METHOD(system), LOAD_CONST('pip install pywin32'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(os), LOAD_METHOD(execv), LOAD_NAME(sys.executable), LOAD_CONST('python'), BUILD_LIST{1}, LOAD_NAME(sys.argv), BINARY_ADD, CALL_METHOD{2}, POP_TOP, POP_EXCEPT, JUMP_FORWARD(to 348), RERAISE

LOAD_NAME(configparser), LOAD_METHOD(ConfigParser), CALL_METHOD, STORE_NAME(config)

LOAD_NAME(os), LOAD_METHOD(system), LOAD_CONST('cls'), CALL_METHOD{1}, POP_TOP

LOAD_NAME(str), LOAD_NAME(datetime.date), LOAD_METHOD(today), CALL_METHOD, CALL_FUNCTION{1}, STORE_NAME(now_date)
LOAD_NAME(os), LOAD_METHOD(getlogin), CALL_METHOD, STORE_NAME(user)
buffor = False
LOAD_CONST('C:/Users/'), LOAD_NAME(user), FORMAT_VALUE{(None, False)}, LOAD_CONST('/AppData/Roaming/.mlauncher'), BUILD_STRING{3}, STORE_NAME(sciezka)
LOAD_CONST('C:/Users/'), LOAD_NAME(user), FORMAT_VALUE{(None, False)}, LOAD_CONST('/AppData/Local/Temp'), BUILD_STRING{3}, STORE_NAME(temp)

LOAD_NAME(sciezka), FORMAT_VALUE{(None, False)}, LOAD_CONST('/bin'), BUILD_STRING{2}, STORE_NAME(sciezkaver)
LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/ver.txt'), BUILD_STRING{2}, STORE_NAME(txtFile)
LOAD_NAME(path), LOAD_METHOD(exists), LOAD_NAME(sciezka), CALL_METHOD{1}, LOAD_CONST(False), COMPARE_OP(==), EXTENDED_ARG{1}, POP_JUMP_IF_FALSE{462}
LOAD_NAME(os), LOAD_METHOD(mkdir), LOAD_NAME(sciezka), CALL_METHOD{1}, POP_TOP
LOAD_NAME(path), LOAD_METHOD(exists), LOAD_NAME(sciezka), FORMAT_VALUE{(None, False)}, LOAD_CONST('/bin'), BUILD_STRING{2}, CALL_METHOD{1}, LOAD_CONST(False), COMPARE_OP(==), EXTENDED_ARG{1}, POP_JUMP_IF_FALSE{500}
LOAD_NAME(os), LOAD_METHOD(mkdir), LOAD_NAME(sciezka), FORMAT_VALUE{(None, False)}, LOAD_CONST('/bin'), BUILD_STRING{2}, CALL_METHOD{1}, POP_TOP

|500|pliki(sciezkaver)
LOAD_NAME(logging.Formatter), LOAD_CONST('%(asctime)s.%(msecs)03d'), LOAD_CONST('%Y-%m-%d,%H:%M:%S'), LOAD_CONST(('fmt', 'datefmt')), CALL_FUNCTION_KW{2}, POP_TOP
LOAD_NAME(logging.basicConfig), LOAD_CONST(('filename', 'format', 'filemode')), CALL_FUNCTION_KW{3}, POP_TOP
LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/logs-setup/latest.log'), BUILD_STRING{2}
LOAD_CONST('%(asctime)s %(message)s')
LOAD_CONST('w')

LOAD_NAME(logging), LOAD_METHOD(getLogger), LOAD_NAME(__name__), CALL_METHOD{1}, STORE_NAME(logger)
LOAD_NAME(coloredlogs.install), LOAD_CONST('DEBUG'), LOAD_NAME(logger), LOAD_CONST(('level', 'logger')), CALL_FUNCTION_KW{2}, POP_TOP

LOAD_NAME(logger), LOAD_METHOD(debug), LOAD_CONST('DEBUG: Starting'), CALL_METHOD{1}, POP_TOP

downloader(
'https://raw.githubusercontent.com/Bre3n/MLauncher/master/files/links.txt', 
txtFile, 
0)


LOAD_NAME(logger), LOAD_METHOD(debug), LOAD_CONST('DEBUG: Downloaded version file'), CALL_METHOD{1}, POP_TOP
open(txtFile), SETUP_WITH(to 646), STORE_NAME(f)
LOAD_NAME(f), LOAD_METHOD(readlines), CALL_METHOD, STORE_NAME(content)
    BUILD_LIST, LOAD_FAST(.0), FOR_ITER(to 18), STORE_FAST(x), LOAD_FAST(x), LOAD_METHOD(strip), CALL_METHOD, LIST_APPEND{2}, JUMP_ABSOLUTE{4}, RETURN_VALUE, LOAD_CONST(code), LOAD_CONST('<listcomp>'), MAKE_FUNCTION, LOAD_NAME(content), GET_ITER, CALL_FUNCTION{1}, STORE_NAME(content), POP_BLOCK, LOAD_CONST(None), DUP_TOP, DUP_TOP, CALL_FUNCTION{3}, POP_TOP, JUMP_FORWARD(to 664), WITH_EXCEPT_START, EXTENDED_ARG{2}, POP_JUMP_IF_TRUE{654}, RERAISE, POP_TOP, POP_TOP, POP_TOP, POP_EXCEPT, POP_TOP
LOAD_NAME(os), LOAD_METHOD(remove), LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/ver.txt'), BUILD_STRING{2}, CALL_METHOD{1}, POP_TOP

LOAD_NAME(path), LOAD_METHOD(exists), LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/version.txt'), BUILD_STRING{2}, CALL_METHOD{1}, LOAD_CONST(False), COMPARE_OP(==), EXTENDED_ARG{3}, POP_JUMP_IF_FALSE{820}
LOAD_NAME(open), LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/version.txt'), BUILD_STRING{2}, LOAD_CONST('w'), CALL_FUNCTION{2}, STORE_NAME(f)
LOAD_NAME(range), LOAD_NAME(int), LOAD_NAME(len(content)), LOAD_CONST(2), BINARY_TRUE_DIVIDE, CALL_FUNCTION{1}, CALL_FUNCTION{1}, GET_ITER, FOR_ITER(to 766), STORE_NAME(i)
LOAD_NAME(f), LOAD_METHOD(write), LOAD_NAME(content), LOAD_NAME(i), BINARY_SUBSCR, FORMAT_VALUE{(None, False)}, LOAD_CONST('\n'), BUILD_STRING{2}, CALL_METHOD{1}, POP_TOP, EXTENDED_ARG{2}, JUMP_ABSOLUTE{738}
LOAD_NAME(f), LOAD_METHOD(close), CALL_METHOD, POP_TOP
LOAD_NAME(logger), LOAD_METHOD(info), LOAD_CONST("INFO: Version file didn't exist"), CALL_METHOD{1}, POP_TOP
LOAD_NAME(logger), LOAD_METHOD(warning), LOAD_CONST('WARNING: Restarting!'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(os), LOAD_METHOD(execv), LOAD_NAME(sys.executable), LOAD_CONST('python'), BUILD_LIST{1}, LOAD_NAME(sys.argv), BINARY_ADD, CALL_METHOD{2}, POP_TOP, EXTENDED_ARG{5}, JUMP_FORWARD(to 2246)

LOAD_NAME(logger), LOAD_METHOD(debug), LOAD_CONST('DEBUG: Starting version comparing'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(open), LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/version.txt'), BUILD_STRING{2}, CALL_FUNCTION{1}, SETUP_WITH(to 882), STORE_NAME(f)
LOAD_NAME(f), LOAD_METHOD(readlines), CALL_METHOD, STORE_NAME(contentv)
    BUILD_LIST, LOAD_FAST(.0), FOR_ITER(to 18), STORE_FAST(x), LOAD_FAST(x), LOAD_METHOD(strip), CALL_METHOD, LIST_APPEND{2}, JUMP_ABSOLUTE{4}, RETURN_VALUE, LOAD_CONST(code), LOAD_CONST('<listcomp>'), MAKE_FUNCTION, LOAD_NAME(contentv), GET_ITER, CALL_FUNCTION{1}, STORE_NAME(contentv), POP_BLOCK, LOAD_CONST(None), DUP_TOP, DUP_TOP, CALL_FUNCTION{3}, POP_TOP, JUMP_FORWARD(to 900), WITH_EXCEPT_START, EXTENDED_ARG{3}, POP_JUMP_IF_TRUE{890}, RERAISE, POP_TOP, POP_TOP, POP_TOP, POP_EXCEPT, POP_TOP
LOAD_NAME(int), LOAD_NAME(len(content)), LOAD_CONST(2), BINARY_TRUE_DIVIDE, CALL_FUNCTION{1}, int(len(contentv)), COMPARE_OP(!=), EXTENDED_ARG{4}, POP_JUMP_IF_FALSE{1040}
LOAD_NAME(print), LOAD_NAME(int), LOAD_NAME(len(content)), LOAD_CONST(2), BINARY_TRUE_DIVIDE, CALL_FUNCTION{1}, CALL_FUNCTION{1}, POP_TOP
print(int(len(contentv)))
LOAD_NAME(logger), LOAD_METHOD(critical), LOAD_CONST("CRITICAL: FILES DON'T HAVE SAME NUMER OF LINES!"), CALL_METHOD{1}, POP_TOP
LOAD_NAME(logger), LOAD_METHOD(debug), LOAD_CONST("DEBUG: Overwritting wrong file with 'None' lines"), CALL_METHOD{1}, POP_TOP
LOAD_NAME(open), LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/version.txt'), BUILD_STRING{2}, LOAD_CONST('w'), CALL_FUNCTION{2}, STORE_NAME(f)
LOAD_NAME(range), LOAD_NAME(int), LOAD_NAME(len(content)), LOAD_CONST(2), BINARY_TRUE_DIVIDE, CALL_FUNCTION{1}, CALL_FUNCTION{1}, GET_ITER, FOR_ITER(to 1040), STORE_NAME(i)
LOAD_NAME(f), LOAD_METHOD(write), LOAD_CONST('None\n'), CALL_METHOD{1}, POP_TOP, EXTENDED_ARG{3}, JUMP_ABSOLUTE{1022}
LOAD_NAME(open), LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/version.txt'), BUILD_STRING{2}, CALL_FUNCTION{1}, SETUP_WITH(to 1092), STORE_NAME(f)
LOAD_NAME(f), LOAD_METHOD(readlines), CALL_METHOD, STORE_NAME(contentv)
    BUILD_LIST, LOAD_FAST(.0), FOR_ITER(to 18), STORE_FAST(x), LOAD_FAST(x), LOAD_METHOD(strip), CALL_METHOD, LIST_APPEND{2}, JUMP_ABSOLUTE{4}, RETURN_VALUE, LOAD_CONST(code), LOAD_CONST('<listcomp>'), MAKE_FUNCTION, LOAD_NAME(contentv), GET_ITER, CALL_FUNCTION{1}, STORE_NAME(contentv), POP_BLOCK, LOAD_CONST(None), DUP_TOP, DUP_TOP, CALL_FUNCTION{3}, POP_TOP, JUMP_FORWARD(to 1110), WITH_EXCEPT_START, EXTENDED_ARG{4}, POP_JUMP_IF_TRUE{1100}, RERAISE, POP_TOP, POP_TOP, POP_TOP, POP_EXCEPT, POP_TOP
LOAD_NAME(range), LOAD_NAME(int), LOAD_NAME(len(content)), LOAD_CONST(2), BINARY_TRUE_DIVIDE, CALL_FUNCTION{1}, CALL_FUNCTION{1}, GET_ITER, EXTENDED_ARG{1}, FOR_ITER(to 1444), STORE_NAME(i)
LOAD_NAME(content), LOAD_NAME(i), BINARY_SUBSCR, LOAD_NAME(contentv), LOAD_NAME(i), BINARY_SUBSCR, COMPARE_OP(!=), EXTENDED_ARG{4}, POP_JUMP_IF_FALSE{1130}
LOAD_NAME(logger), LOAD_METHOD(warning), CALL_METHOD{1}, POP_TOP
LOAD_CONST("WARNING: Lines didn't match   "), LOAD_NAME(content), LOAD_NAME(i), BINARY_SUBSCR, FORMAT_VALUE{(None, False)}, LOAD_CONST('!='), LOAD_NAME(contentv), LOAD_NAME(i), BINARY_SUBSCR, FORMAT_VALUE{(None, False)}, BUILD_STRING{4}

LOAD_NAME(content), LOAD_NAME(i), BINARY_SUBSCR, LOAD_METHOD(replace), LOAD_CONST(' '), LOAD_CONST(''), CALL_METHOD{2}, STORE_NAME(bufor)
LOAD_NAME(bufor), LOAD_METHOD(split), LOAD_CONST('=='), CALL_METHOD{1}, STORE_NAME(bufor)
LOAD_NAME(bufor), LOAD_CONST(0), BINARY_SUBSCR, LOAD_METHOD(split), LOAD_CONST('.'), CALL_METHOD{1}, STORE_NAME(checkzip)
LOAD_NAME(logger), LOAD_METHOD(debug), LOAD_CONST('DEBUG: Downloading   '), LOAD_NAME(bufor), LOAD_CONST(0), BINARY_SUBSCR, FORMAT_VALUE{(None, False)}, BUILD_STRING{2}, CALL_METHOD{1}, POP_TOP
LOAD_NAME(downloader), CALL_FUNCTION{3}, POP_TOP
LOAD_NAME(content), LOAD_NAME(i), LOAD_NAME(int), LOAD_NAME(len(content)), LOAD_CONST(2), BINARY_TRUE_DIVIDE, CALL_FUNCTION{1}, BINARY_ADD, BINARY_SUBSCR
LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/'), LOAD_NAME(bufor), LOAD_CONST(0), BINARY_SUBSCR, FORMAT_VALUE{(None, False)}, BUILD_STRING{3}
LOAD_CONST(1)

print(' ')
LOAD_NAME(logger), LOAD_METHOD(debug), LOAD_CONST('DEBUG: Download complete'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(checkzip), LOAD_CONST(1), BINARY_SUBSCR, LOAD_CONST('zip'), COMPARE_OP(==), EXTENDED_ARG{4}, POP_JUMP_IF_FALSE{1130}
LOAD_NAME(logger), LOAD_METHOD(info), LOAD_CONST('INFO: Detected zip file. Extractings'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(zipfile), LOAD_METHOD(ZipFile), LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/'), LOAD_NAME(bufor), LOAD_CONST(0), BINARY_SUBSCR, FORMAT_VALUE{(None, False)}, BUILD_STRING{3}, LOAD_CONST('r'), CALL_METHOD{2}, SETUP_WITH(to 1398), STORE_NAME(zipObj)
LOAD_NAME(zipObj), LOAD_METHOD(extractall), LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/'), LOAD_NAME(checkzip), LOAD_CONST(0), BINARY_SUBSCR, FORMAT_VALUE{(None, False)}, BUILD_STRING{3}, CALL_METHOD{1}, POP_TOP, POP_BLOCK, LOAD_CONST(None), DUP_TOP, DUP_TOP, CALL_FUNCTION{3}, POP_TOP, JUMP_FORWARD(to 1416), WITH_EXCEPT_START, EXTENDED_ARG{5}, POP_JUMP_IF_TRUE{1406}, RERAISE, POP_TOP, POP_TOP, POP_TOP, POP_EXCEPT, POP_TOP
LOAD_NAME(os), LOAD_METHOD(remove), LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/'), LOAD_NAME(bufor), LOAD_CONST(0), BINARY_SUBSCR, FORMAT_VALUE{(None, False)}, BUILD_STRING{3}, CALL_METHOD{1}, POP_TOP, EXTENDED_ARG{4}, JUMP_ABSOLUTE{1130}
LOAD_NAME(open), LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/version.txt'), BUILD_STRING{2}, LOAD_CONST('w'), CALL_FUNCTION{2}, STORE_NAME(f)
LOAD_NAME(range), LOAD_NAME(int), LOAD_NAME(len(content)), LOAD_CONST(2), BINARY_TRUE_DIVIDE, CALL_FUNCTION{1}, CALL_FUNCTION{1}, GET_ITER, FOR_ITER(to 1508), STORE_NAME(i)
LOAD_NAME(f), LOAD_METHOD(write), LOAD_NAME(content), LOAD_NAME(i), BINARY_SUBSCR, FORMAT_VALUE{(None, False)}, LOAD_CONST('\n'), BUILD_STRING{2}, CALL_METHOD{1}, POP_TOP, EXTENDED_ARG{5}, JUMP_ABSOLUTE{1480}
LOAD_NAME(f), LOAD_METHOD(close), CALL_METHOD, POP_TOP
LOAD_NAME(logger), LOAD_METHOD(debug), LOAD_CONST('DEBUG: Overwritting old version file'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(logger), LOAD_METHOD(debug), LOAD_CONST('DEBUG: Comparing files in directory'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(range), LOAD_NAME(int), LOAD_NAME(len(content)), LOAD_CONST(2), BINARY_TRUE_DIVIDE, CALL_FUNCTION{1}, CALL_FUNCTION{1}, GET_ITER, EXTENDED_ARG{1}, FOR_ITER(to 1896), STORE_NAME(i)
LOAD_NAME(content), LOAD_NAME(i), BINARY_SUBSCR, LOAD_METHOD(replace), LOAD_CONST(' '), LOAD_CONST(''), CALL_METHOD{2}, STORE_NAME(bufor)
LOAD_NAME(bufor), LOAD_METHOD(split), LOAD_CONST('=='), CALL_METHOD{1}, STORE_NAME(bufor)
LOAD_NAME(bufor), LOAD_CONST(0), BINARY_SUBSCR, LOAD_METHOD(split), LOAD_CONST('.'), CALL_METHOD{1}, STORE_NAME(checkzip)
LOAD_NAME(bufor), LOAD_CONST(0), BINARY_SUBSCR, STORE_NAME(buforr)
LOAD_NAME(checkzip), LOAD_CONST(1), BINARY_SUBSCR, LOAD_CONST('zip'), COMPARE_OP(==), EXTENDED_ARG{6}, POP_JUMP_IF_FALSE{1636}
LOAD_NAME(checkzip), LOAD_CONST(0), BINARY_SUBSCR, LOAD_NAME(bufor), LOAD_CONST(0), STORE_SUBSCR
LOAD_NAME(path), LOAD_METHOD(exists), LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/'), LOAD_NAME(bufor), LOAD_CONST(0), BINARY_SUBSCR, FORMAT_VALUE{(None, False)}, BUILD_STRING{3}, CALL_METHOD{1}, LOAD_CONST(False), COMPARE_OP(==), EXTENDED_ARG{6}, POP_JUMP_IF_FALSE{1556}
LOAD_NAME(logger), LOAD_METHOD(warning), CALL_METHOD{1}, POP_TOP
LOAD_CONST('WARNING: There is no file named   '), LOAD_NAME(bufor), LOAD_CONST(0), BINARY_SUBSCR, FORMAT_VALUE{(None, False)}, LOAD_CONST('   in directory'), BUILD_STRING{3}

LOAD_NAME(logger), LOAD_METHOD(debug), LOAD_CONST('DEBUG: Downloading   '), LOAD_NAME(bufor), LOAD_CONST(0), BINARY_SUBSCR, FORMAT_VALUE{(None, False)}, BUILD_STRING{2}, CALL_METHOD{1}, POP_TOP
LOAD_NAME(downloader), CALL_FUNCTION{3}, POP_TOP
LOAD_NAME(content), LOAD_NAME(i), LOAD_NAME(int), LOAD_NAME(len(content)), LOAD_CONST(2), BINARY_TRUE_DIVIDE, CALL_FUNCTION{1}, BINARY_ADD, BINARY_SUBSCR
LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/'), LOAD_NAME(buforr), FORMAT_VALUE{(None, False)}, BUILD_STRING{3}
LOAD_CONST(1)

print(' ')
LOAD_NAME(logger), LOAD_METHOD(debug), LOAD_CONST('DEBUG: Download complete'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(checkzip), LOAD_CONST(1), BINARY_SUBSCR, LOAD_CONST('zip'), COMPARE_OP(==), EXTENDED_ARG{6}, POP_JUMP_IF_FALSE{1556}
LOAD_NAME(logger), LOAD_METHOD(info), LOAD_CONST('INFO: Detected zip file. Extracting'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(zipfile), LOAD_METHOD(ZipFile), LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/'), LOAD_NAME(buforr), FORMAT_VALUE{(None, False)}, BUILD_STRING{3}, LOAD_CONST('r'), CALL_METHOD{2}, SETUP_WITH(to 1854), STORE_NAME(zipObj)
LOAD_NAME(zipObj), LOAD_METHOD(extractall), LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/'), LOAD_NAME(checkzip), LOAD_CONST(0), BINARY_SUBSCR, FORMAT_VALUE{(None, False)}, BUILD_STRING{3}, CALL_METHOD{1}, POP_TOP, POP_BLOCK, LOAD_CONST(None), DUP_TOP, DUP_TOP, CALL_FUNCTION{3}, POP_TOP, JUMP_FORWARD(to 1872), WITH_EXCEPT_START, EXTENDED_ARG{7}, POP_JUMP_IF_TRUE{1862}, RERAISE, POP_TOP, POP_TOP, POP_TOP, POP_EXCEPT, POP_TOP
LOAD_NAME(os), LOAD_METHOD(remove), LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/'), LOAD_NAME(buforr), FORMAT_VALUE{(None, False)}, BUILD_STRING{3}, CALL_METHOD{1}, POP_TOP, EXTENDED_ARG{6}, JUMP_ABSOLUTE{1556}
LOAD_NAME(logger), LOAD_METHOD(debug), LOAD_CONST('DEBUG: Program process complete'), CALL_METHOD{1}, POP_TOP
LOAD_NAME(logging), LOAD_METHOD(shutdown), CALL_METHOD, POP_TOP
LOAD_NAME(winshell), LOAD_METHOD(desktop), CALL_METHOD, STORE_NAME(desktop)
LOAD_NAME(os), LOAD_METHOD(getcwd), CALL_METHOD, STORE_NAME(cwd)
LOAD_NAME(path), LOAD_METHOD(exists), LOAD_NAME(sciezka), FORMAT_VALUE{(None, False)}, LOAD_CONST('/cache/setup.txt'), BUILD_STRING{2}, CALL_METHOD{1}, EXTENDED_ARG{7}, POP_JUMP_IF_FALSE{2004}
LOAD_NAME(open), LOAD_NAME(sciezka), FORMAT_VALUE{(None, False)}, LOAD_CONST('/cache/setup.txt'), BUILD_STRING{2}, LOAD_CONST('r'), CALL_FUNCTION{2}, STORE_NAME(f)
LOAD_NAME(os), LOAD_METHOD(remove), LOAD_NAME(f), LOAD_METHOD(read), CALL_METHOD, FORMAT_VALUE{(None, False)}, CALL_METHOD{1}, POP_TOP
LOAD_NAME(os), LOAD_METHOD(remove), LOAD_NAME(sciezka), FORMAT_VALUE{(None, False)}, LOAD_CONST('/cache/setup.txt'), BUILD_STRING{2}, CALL_METHOD{1}, POP_TOP
LOAD_NAME(f), LOAD_METHOD(close), CALL_METHOD, POP_TOP
EXTENDED_ARG{8}, POP_JUMP_IF_FALSE{2112}, EXTENDED_ARG{8}, POP_JUMP_IF_FALSE{2112}
LOAD_NAME(cwd), LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, COMPARE_OP(!=)
LOAD_NAME(cwd), LOAD_CONST('C:\\Users/'), LOAD_NAME(user), FORMAT_VALUE{(None, False)}, LOAD_CONST('\\Desktop\\Projekty\\LauncherUi'), BUILD_STRING{3}, COMPARE_OP(!=)

LOAD_NAME(path), LOAD_METHOD(exists), LOAD_NAME(sciezka), FORMAT_VALUE{(None, False)}, LOAD_CONST('/cache'), BUILD_STRING{2}, CALL_METHOD{1}, LOAD_CONST(False), COMPARE_OP(==), EXTENDED_ARG{8}, POP_JUMP_IF_FALSE{2072}
LOAD_NAME(os), LOAD_METHOD(mkdir), LOAD_NAME(sciezka), FORMAT_VALUE{(None, False)}, LOAD_CONST('/cache'), BUILD_STRING{2}, CALL_METHOD{1}, POP_TOP
LOAD_NAME(open), LOAD_NAME(sciezka), FORMAT_VALUE{(None, False)}, LOAD_CONST('/cache/setup.txt'), BUILD_STRING{2}, LOAD_CONST('w'), CALL_FUNCTION{2}, STORE_NAME(f)
LOAD_NAME(f), LOAD_METHOD(write), LOAD_NAME(cwd), FORMAT_VALUE{(None, False)}, LOAD_CONST('\\setup.py'), BUILD_STRING{2}, CALL_METHOD{1}, POP_TOP
LOAD_NAME(f), LOAD_METHOD(close), CALL_METHOD, POP_TOP
LOAD_NAME(path), LOAD_METHOD(exists), LOAD_NAME(desktop), FORMAT_VALUE{(None, False)}, LOAD_CONST('/MLauncher.lnk'), BUILD_STRING{2}, CALL_METHOD{1}, LOAD_CONST(False), COMPARE_OP(==), EXTENDED_ARG{8}, POP_JUMP_IF_FALSE{2210}
LOAD_NAME(os.path), LOAD_METHOD(join), LOAD_NAME(desktop), LOAD_CONST('MLauncher.lnk'), CALL_METHOD{2}, STORE_NAME(path)
LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/setup.py'), BUILD_STRING{2}, STORE_NAME(target)
LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/icons/1x/icon.ico'), BUILD_STRING{2}, STORE_NAME(icon)
LOAD_NAME(win32com.client), LOAD_METHOD(Dispatch), LOAD_CONST('WScript.Shell'), CALL_METHOD{1}, STORE_NAME(shell)
LOAD_NAME(shell), LOAD_METHOD(CreateShortCut), LOAD_NAME(path), CALL_METHOD{1}, STORE_NAME(shortcut)
LOAD_NAME(target), LOAD_NAME(shortcut), STORE_ATTR(Targetpath)
LOAD_NAME(icon), LOAD_NAME(shortcut), STORE_ATTR(IconLocation)
LOAD_NAME(shortcut), LOAD_METHOD(save), CALL_METHOD, POP_TOP
LOAD_NAME(os), LOAD_METHOD(chdir), LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/'), BUILD_STRING{2}, CALL_METHOD{1}, POP_TOP
LOAD_NAME(subprocess), LOAD_METHOD(call), LOAD_CONST('python'), LOAD_NAME(sciezkaver), FORMAT_VALUE{(None, False)}, LOAD_CONST('/main.py'), BUILD_STRING{2}, BUILD_LIST{2}, CALL_METHOD{1}, POP_TOP, return |2246|None
